"""Sphinx configuration for the PyNeurale documentation."""

from __future__ import annotations

import sys
from importlib import import_module
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "src"
DOXYGEN_XML_DIR = ROOT / "docs" / "_build" / "doxygen" / "xml"

sys.path.insert(0, str(SOURCE_DIR))

project = "PyNeurale"
author = "PyNeurale contributors"
copyright = "2026, PyNeurale contributors"

release = import_module("neurale").__version__
if release == "0+unknown":
    raise RuntimeError(
        "PyNeurale version is unavailable; install the checkout before building docs"
    )
version = release

extensions = [
    "breathe",
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

source_suffix = {
    ".md": "markdown",
    ".rst": "restructuredtext",
}
master_doc = "index"
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "fieldlist",
]

autosummary_generate = True
autodoc_member_order = "bysource"
autodoc_typehints = "description"
autodoc_typehints_format = "short"
napoleon_google_docstring = False
napoleon_numpy_docstring = True

# Breathe requires Doxygen XML generated by tools/build_docs.py.
if not (DOXYGEN_XML_DIR / "index.xml").is_file():
    raise RuntimeError(
        f"Doxygen XML is missing at {DOXYGEN_XML_DIR}. The C++ API pages are generated "
        "from it, so Doxygen has to run before Sphinx: use `python tools/build_docs.py` "
        "(it runs both) rather than calling sphinx-build directly, and make sure Doxygen "
        "is installed and on PATH."
    )

breathe_projects = {
    "pyneurale": str(DOXYGEN_XML_DIR),
}
breathe_default_project = "pyneurale"
breathe_default_members = ("members",)

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
}

html_theme = "pydata_sphinx_theme"
html_title = f"PyNeurale {version}"
html_static_path = ["_static"]
html_theme_options = {
    "collapse_navigation": False,
    "navigation_depth": 4,
    "show_toc_level": 2,
    "github_url": "https://github.com/RanXingchen/pyneurale",
}

templates_path = ["_templates"]
